package alex.silantev.dronzilla.enums;

public enum ErrorCode {
    IO_ERROR,
    RESOURCE_NOT_FOUND,
    VALIDATION_ERROR,
    DRONE_SERIAL_NUMBER_NOT_UNIQUE,
    DRONE_NOT_FOUND,
    DRONE_IS_BUSY,
    DRONE_MUST_BE_LOADED,
    DRONE_LOW_BATTERY,
    DRONE_INVALID_STATE,
    OVERWEIGHT_CARGO
}
